export const listSkills = [
    {id: 1, name: 'ReactJS', icon: '/public/img/react.png'},
    {id: 2, name: 'NodeJS', icon: '/public/img/nodejs.png'},
    {id: 3, name: 'ExpressJS', icon: '/public/img/node.png'},
    {id: 4, name: 'PostgreSQL', icon: '/public/img/postgreesql.png'},
    {id: 5, name: 'JavaScript', icon: '/public/img/javascript.png'},
    {id: 6, name: 'Chakra UI', icon: '/public/img/chakra-ui.png'},
    {id: 7, name: 'Firebase', icon: '/public/img/firebase.png'},
    {id: 8, name: 'MongoDB', icon: '/public/img/mongodb.png'},
    {id: 9, name: 'HTML 5', icon: '/public/img/html-5.png'},
    {id: 10, name: 'CSS 3', icon: '/public/img/css3.png'},
    {id: 11, name: 'Material UI', icon: '/public/img/material-ui.png'},
    {id: 12, name: 'Bootstrap', icon: '/public/img/bootstrap.png'},
    {id: 13, name: 'MySQL', icon: '/public/img/mysql.png'},   
    {id: 14, name: 'PHP', icon: '/public/img/php.png'},
    {id: 15, name: 'Redux', icon: '/public/img/redux.png'},
    {id: 16, name: 'Sass', icon: '/public/img/sass.png'},
    {id: 17, name: 'Tailwind', icon: '/public/img/tailwind.png'},
    {id: 18, name: 'Wordpress', icon: '/public/img/wordpress.png'},
]